### ISSUE TITLE
Random Replication Algorithm

### ISSUE THREAD

**Issue by hugoLucas** [hugoLucas/replication#2]
Write a random replication algorithm that takes an existing data center topology and randomly replicates virtual machines and places them in to new physical hosts. 

Algorithm class should have the following methods: 
- **allocate** : which triggers the algorithm to allocate a set of virtual machines 
- **get_cost**: returns the total vm pair communication cost

**Comment by Alexander-Ing** [comment]
Professor has noted that this is not necessary.
